#!/usr/bin/env python3
# Copyright 2026 HANUMAN — MIT License.
#
# Build the mujoco_ros2_control deployment scene: a generated Mars terrain
# (hfield + draped HiRISE orthophoto + boulders) with the G1 spawned standing on
# the flattest nearby spot. The terrain is wrapped in a static body offset so
# that flat spot sits at the world origin under the robot's 'stand' keyframe.
#
# Usage:
#   python3 make_mars_nav_scene.py <terrain_dir> <g1_include> <out_scene.xml>
# e.g.
#   python3 make_mars_nav_scene.py unitree_g1_mjcf/mars_nav_1k g1_mars.xml \
#           unitree_g1_mjcf/mars_nav_scene.xml

import os
import re
import sys
from pathlib import Path

import mujoco
import numpy as np

MARS_GRAVITY = 3.72
SPAWN_PELVIS_Z = 0.80   # robot 'stand' keyframe base height above ground


def find_flat_spot(terrain_model_xml: Path, search_half=180.0, step=8.0, probe=1.5):
    """Ray-cast a grid over the terrain; return (x, y, ground_z) of the flattest
    ~3 m patch (minimal height spread among center + 4 neighbours)."""
    m = mujoco.MjModel.from_xml_path(str(terrain_model_xml))
    d = mujoco.MjData(m)
    mujoco.mj_forward(m, d)
    top = float(m.hfield_size[0][2]) + 50.0

    def ground_z(x, y):
        pnt = np.array([x, y, top], dtype=np.float64)
        vec = np.array([0, 0, -1], dtype=np.float64)
        gid = np.zeros(1, dtype=np.int32)
        dist = mujoco.mj_ray(m, d, pnt, vec, None, 1, -1, gid)
        return (top - dist) if dist >= 0 else None

    best = None
    xs = np.arange(-search_half, search_half + 1, step)
    for x in xs:
        for y in xs:
            zc = ground_z(x, y)
            if zc is None:
                continue
            neigh = [ground_z(x + dx, y + dy)
                     for dx, dy in ((probe, 0), (-probe, 0), (0, probe), (0, -probe))]
            if any(z is None for z in neigh):
                continue
            spread = max([zc] + neigh) - min([zc] + neigh)
            if best is None or spread < best[0]:
                best = (spread, x, y, zc)
    _, x, y, z = best
    print(f"  flattest spawn: x={x:.1f} y={y:.1f} ground_z={z:.2f} "
          f"(local spread {best[0]*100:.1f} cm)")
    return float(x), float(y), float(z)


def build_scene(terrain_dir: Path, g1_include: str, out_path: Path) -> None:
    terrain_dir = terrain_dir.resolve()
    model_xml = terrain_dir / "model.xml"
    text = model_xml.read_text()

    site_id = terrain_dir.name
    hfield_size = re.search(r'<hfield[^>]*size="([^"]+)"', text).group(1)

    # Emit asset paths relative so the generated scene is portable. MuJoCo
    # resolves them per asset type: hfield files relative to the model's
    # `meshdir`, textures relative to the model directory. The robot include
    # sets `meshdir`, so read it and make the hfield path relative to that;
    # otherwise the two would need different prefixes and one would break.
    out_dir = out_path.resolve().parent
    include_path = (out_dir / g1_include).resolve()
    meshdir = out_dir
    if include_path.exists():
        m = re.search(r'<compiler[^>]*meshdir="([^"]+)"', include_path.read_text())
        if m:
            meshdir = (out_dir / m.group(1)).resolve()
    png = os.path.relpath((terrain_dir / f"{site_id}.png").resolve(), meshdir)
    albedo = os.path.relpath((terrain_dir / f"{site_id}_albedo.png").resolve(), out_dir)

    # Copy the terrain + boulder geoms verbatim (keep asset names).
    worldbody = re.search(r"<worldbody>(.*)</worldbody>", text, re.S).group(1)
    geoms = "\n".join("      " + ln.strip()
                      for ln in worldbody.strip().splitlines())

    x_s, y_s, z_s = find_flat_spot(model_xml)

    scene = f"""<!-- HANUMAN Mars navigation scene for mujoco_ros2_control.
     GENERATED by scripts/make_mars_nav_scene.py — do not edit by hand.
     Real HiRISE terrain '{site_id}' (orthophoto draped) + G1, Mars gravity.
     The terrain is offset so the flattest spot sits under the robot's spawn. -->
<mujoco model="hanuman_mars_nav">
  <include file="{g1_include}"/>

  <option gravity="0 0 -{MARS_GRAVITY:.2f}" timestep="0.002">
    <flag warmstart="enable"/>
  </option>
  <statistic center="0 0 0.8" extent="6"/>

  <visual>
    <headlight diffuse="0.8 0.6 0.4" ambient="0.3 0.2 0.15" specular="0.1 0.1 0.1"/>
    <rgba haze="0.6 0.35 0.15 1"/>
    <map znear="0.01" zfar="2000"/>
    <quality shadowsize="4096"/>
    <global azimuth="140" elevation="-20" offwidth="1280" offheight="720"/>
  </visual>

  <asset>
    <texture name="sky" type="skybox" builtin="gradient"
             rgb1="0.75 0.55 0.35" rgb2="0.35 0.15 0.05" width="512" height="3072"/>
    <hfield name="{site_id}_hfield" file="{png}" size="{hfield_size}"/>
    <texture name="{site_id}_tex" type="2d" file="{albedo}"/>
    <material name="{site_id}_mat" texture="{site_id}_tex" texrepeat="1 1"
              texuniform="false" specular="0.02" roughness="0.98"/>
    <material name="{site_id}_rock" rgba="0.4 0.27 0.18 1" specular="0.05" roughness="0.95"/>
  </asset>

  <worldbody>
    <light name="sun" pos="100 100 200" dir="-0.3 -0.3 -1"
           diffuse="1.2 0.9 0.6" specular="0.3 0.2 0.1" castshadow="true"/>
    <light name="fill" pos="0 0 80" dir="0 0 -1"
           diffuse="0.3 0.2 0.15" specular="0 0 0" castshadow="false"/>

    <!-- Terrain + boulders, offset so the flat spawn spot is at the world origin. -->
    <body name="mars_terrain" pos="{-x_s:.3f} {-y_s:.3f} {-z_s:.3f}">
{geoms}
    </body>
  </worldbody>
</mujoco>
"""
    out_path.write_text(scene)
    print(f"  wrote {out_path}")


if __name__ == "__main__":
    terrain_dir = Path(sys.argv[1])
    g1_include = sys.argv[2]
    out_path = Path(sys.argv[3])
    build_scene(terrain_dir, g1_include, out_path)
